const books = [
  {
    id: 1,
    image: require('../../../assets/BilbPhotos/livre-(10).png'),
    title: 'khbjhb',
    type: 'painting',
    Author: 'vgrgbrb',
    Year: 'fvcfbgrt',
    Isbn: 'brfttfg',
    Price: 'gfrggh',
    Description: 'frcbtrfbcgtybtxcgtbytb',
  },
  {
    id: 2,
    image: require('../../../assets/BilbPhotos/livre-(1).png'),
    title: 'khbjhb',
    type: 'painting',
    Author: 'vgrgbrb',
    Year: 'fvcfbgrt',
    Isbn: 'brfttfg',
    Price: 'gfrggh',
    Description: 'frcbtrfbcgtybtxcgtbytb',
  },
  {
    id: 3,
    image: require('../../../assets/BilbPhotos/livre-(10).png'),
    title: 'khbjhb',
    type: 'painting',
    Author: 'vgrgbrb',
    Year: 'fvcfbgrt',
    Isbn: 'brfttfg',
    Price: 'gfrggh',
    Description: 'frcbtrfbcgtybtxcgtbytb',
  },
  {
    id: 4,
    image: require('../../../assets/BilbPhotos/livre-(16).png'),
    title: 'khbjhb',
    type: 'books',
    Author: 'vgrgbrb',
    Year: 'fvcfbgrt',
    Isbn: 'brfttfg',
    Price: 'gfrggh',
    Description: 'frcbtrfbcgtybtxcgtbytb',
  },
  {
    id: 5,
    image: require('../../../assets/BilbPhotos/livre-(16).png'),
    title: 'khbjhb',
    type: 'books',
    Author: 'vgrgbrb',
    Year: 'fvcfbgrt',
    Isbn: 'brfttfg',
    Price: 'gfrggh',
    Description: 'frcbtrfbcgtybtxcgtbytb',
  },
  {
    id: 6,
    image: require('../../../assets/BilbPhotos/livre-(16).png'),
    title: 'khbjhb',
    type: 'books',
    Author: 'vgrgbrb',
    Year: 'fvcfbgrt',
    Isbn: 'brfttfg',
    Price: 'gfrggh',
    Description: 'frcbtrfbcgtybtxcgtbytb',
  },
  {
    id: 7,
    image: require('../../../assets/BilbPhotos/livre-(16).png'),
    title: 'khbjhb',
    type: 'exchange',
    Author: 'vgrgbrb',
    Year: 'fvcfbgrt',
    Isbn: 'brfttfg',
    Price: 'gfrggh',
    Description: 'frcbtrfbcgtybtxcgtbytb',
  },
  {
    id: 8,
    image: require('../../../assets/BilbPhotos/livre-(16).png'),
    title: 'khbjhb',
    type: 'exchange',
    Author: 'vgrgbrb',
    Year: 'fvcfbgrt',
    Isbn: 'brfttfg',
    Price: 'gfrggh',
    Description: 'frcbtrfbcgtybtxcgtbytb',
  },
  {
    id: 9,
    image: require('../../../assets/BilbPhotos/livre-(16).png'),
    title: 'khbjhb',
    type: 'painting',
    Author: 'vgrgbrb',
    Year: 'fvcfbgrt',
    Isbn: 'brfttfg',
    Price: 'gfrggh',
    Description: 'frcbtrfbcgtybtxcgtbytb',
  },
  {
    id: 10,
    image: require('../../../assets/BilbPhotos/livre-(16).png'),
    title: 'khbjhb',
    type: 'exchange',
    Author: 'vgrgbrb',
    Year: 'fvcfbgrt',
    Isbn: 'brfttfg',
    Price: 'gfrggh',
    Description: 'frcbtrfbcgtybtxcgtbytb',
  },
];

export default books;
